do not edit metadata when not in qa_control list

diff --git a/init.d/Imaging.init b/init.d/Imaging.init
--- a/init.d/Imaging.init
+++ b/init.d/Imaging.init
@@ -23,64 +23,64 @@ plackup_opts="-s Starman -E development bin/app.pl --access-log $imaging_log"
 RET=0
 
 pid_exists (){
-        pid=$(get_pid)
-        re=0
-        if [ -z $pid ];then
-                re=1
-        else
-                kill -0 $pid &> /dev/null
-                re=$?
-        fi
-        echo $re
+  pid=$(get_pid)
+  re=0
+  if [ -z $pid ];then
+    re=1
+  else
+    kill -0 $pid &> /dev/null
+    re=$?
+  fi
+  echo $re
 }
 get_pid () {
-        cat $pidfile 2> /dev/null
+  cat $pidfile 2> /dev/null
 }
 
 case "$1" in
   start)
-        echo "starting imaging"
+    echo "starting imaging"
     RET=$(pid_exists)
     if [ "$RET" -eq "0" ];then
-            echo "imaging already running"
-                exit 0;
-        fi
-        cd $imaging_home
+      echo "imaging already running"
+      exit 0;
+    fi
+    cd $imaging_home
     plackup $plackup_opts 1> /dev/null 2> $imaging_error &
     RET=$?
-        PID=$!
+    PID=$!
     if [ "$RET" -eq "0" ];then
-        echo $PID > $pidfile
+      echo $PID > $pidfile
     echo "imaging started"
     else
-        echo "imaging could not be started"
+      echo "imaging could not be started"
     fi
   ;;
   stop)
-        echo "shutting down imaging"
-        RET=$(pid_exists)
+    echo "shutting down imaging"
+    RET=$(pid_exists)
     if [ ! "$RET" -eq "0" ];then
-                echo "imaging already stopped"
-                exit 0
-        fi
+      echo "imaging already stopped"
+      exit 0
+    fi
     RET=$?
-        p=$(get_pid)
-        kill -15 $p
-        rm -f $pidfile
+    p=$(get_pid)
+    kill -15 $p
+    rm -f $pidfile
   ;;
   status)
-        RET=$(pid_exists)
-        if [ "$RET" -eq "0" ];then
-                echo "imaging is running"
-        else
-                echo "imaging is not running"
-        fi
+    RET=$(pid_exists)
+    if [ "$RET" -eq "0" ];then
+      echo "imaging is running"
+    else
+      echo "imaging is not running"
+    fi
   ;;
   restart)
-        $0 stop
-        echo "waiting for master to finish off the workers.."
-        sleep 2
-        $0 start
+    $0 stop
+    echo "waiting for master to finish off the workers.."
+    sleep 2
+    $0 start
   ;;
   *)
     echo "Usage: $N {start|stop|status|restart}" >&2
