change init script

diff --git a/init.d/Imaging.init b/init.d/Imaging.init
--- a/init.d/Imaging.init
+++ b/init.d/Imaging.init
@@ -18,69 +18,69 @@ dirname_error=`dirname $imaging_error`
 test -d $dirname_error || mkdir -p $dirname_error || exit 1
 dirname_log=`dirname $imaging_log`
 test -d $dirname_log || mkdir -p $dirname_log || exit 1
-plackup_opts="-s Starman -E development bin/app.pl --access-log $imaging_log"
+plackup_opts="-s Starman -E development $imaging_home/bin/app.pl --access-log $imaging_log"
 
 RET=0
 
 pid_exists (){
-  pid=$(get_pid)
-  re=0
-  if [ -z $pid ];then
-    re=1
-  else
-    kill -0 $pid &> /dev/null
-    re=$?
-  fi
-  echo $re
+	pid=$(get_pid)
+	re=0
+	if [ -z $pid ];then
+		re=1
+	else
+		kill -0 $pid &> /dev/null
+		re=$?
+	fi 
+	echo $re
 }
 get_pid () {
-  cat $pidfile 2> /dev/null
+	cat $pidfile 2> /dev/null
 }
 
 case "$1" in
   start)
-    echo "starting imaging"
+	echo "starting imaging"
     RET=$(pid_exists)
     if [ "$RET" -eq "0" ];then
-      echo "imaging already running"
-      exit 0;
-    fi
-    cd $imaging_home
-    plackup $plackup_opts 1> /dev/null 2> $imaging_error &
+	    echo "imaging already running"
+		exit 0;
+	fi
+    
+    sudo -u imaging /usr/local/bin/plackup $plackup_opts 1> /dev/null 2> $imaging_error &
     RET=$?
-    PID=$!
+	PID=$!
     if [ "$RET" -eq "0" ];then
-      echo $PID > $pidfile
+	echo $PID > $pidfile
     echo "imaging started"
     else
-      echo "imaging could not be started"
+        echo "imaging could not be started"
     fi
   ;;
   stop)
-    echo "shutting down imaging"
-    RET=$(pid_exists)
+	echo "shutting down imaging"
+	RET=$(pid_exists)
     if [ ! "$RET" -eq "0" ];then
-      echo "imaging already stopped"
-      exit 0
-    fi
+		echo "imaging already stopped"
+		exit 0
+	fi
     RET=$?
-    p=$(get_pid)
-    kill -15 $p
-    rm -f $pidfile
+	p=$(get_pid)	
+	kill -15 $p
+	rm -f $pidfile
   ;;
   status)
-    RET=$(pid_exists)
-    if [ "$RET" -eq "0" ];then
-      echo "imaging is running"
-    else
-      echo "imaging is not running"
-    fi
+	RET=$(pid_exists)
+	if [ "$RET" -eq "0" ];then
+		echo "imaging is running"
+	else
+		echo "imaging is not running"
+	fi
   ;;
   restart)
-    $0 stop
-    echo "waiting for master to finish off the workers.."
-    sleep 2
-    $0 start
+	$0 stop
+	echo "waiting for master to finish off the workers.."
+	sleep 2
+	$0 start
   ;;
   *)
     echo "Usage: $N {start|stop|status|restart}" >&2
